<script>
    var MeanbeeBaseUrl = "<?php echo Mage::getBaseUrl() ?>";

    TogetherJSConfig_toolName = "<?php echo $this->__('Shopping Assistant') ?>";
    TogetherJSConfig_siteName = "<?php echo Mage::app()->getWebsite()->getName() ?>";
    TogetherJSConfig_suppressInvite = true;
    TogetherJSConfig_youtube = true;

    <?php /** @var $customer Mage_Customer_Model_Customer */ ?>
    <?php $customer = Mage::helper('customer')->getCustomer(); ?>
    <?php if ($customer): ?>
    TogetherJSConfig_getUserName = function () {
        return "<?php echo $customer->getFirstname() . " " . $customer->getLastname(); ?>";
    };
    TogetherJSConfig_getEmail = function () {
        return "<?php echo $customer->getEmail() ?>";
    };
    TogetherJSConfig_getUserAvatar = function () {
        return "<?php echo "http://www.gravatar.com/avatar/". md5(strtolower(trim($customer->getEmail()))); ?>";
    };
    TogetherJSConfig_getUserColor = function () {
        return '#<?php echo substr(md5(rand()), 0, 6); ?>';
    };
    <?php endif; ?>

    TogetherJSConfig_on_ready = function () {
       document.fire('togetherjs:ready');
    };
</script>
<button class="button button-shopping-assistant" data-shoppingassistant-start><span><span>Request Shopping Assistant</span></span></button>